nbVies = 8

mots = [
    "Aquarium",
    "Araignee",
    "Arbalete",
    "Archipel",
    "Banquise",
    "Batterie",
    "Brocante",
    "Brouhaha",
    "Capeline",
    "Clavecin",
    "Cloporte",
    "Debutant",
    "Diapason",
    "Gangster",
    "Gothique",
    "Hautbois",
    "Herisson",
    "Logiciel",
    "Objectif",
    "Paranoia",
    "Parcours",
    "Pastiche",
    "Question",
    "Quetsche",
    "Scarabee",
    "Scorpion",
    "Symptome",
    "Tabouret",
    "Tomahawk",
    "Toujours",
    "Tourisme",
    "Triangle",
    "Utopique"
]
